version: '3.8'

networks:
  hltv_manager_net:
    external: false

services:
  hltv_manager:
    image: ghcr.io/wesstorn/hltv-manager:${VERSION}
    container_name: hltv_manager
    networks:
     - hltv_manager_net
    ports:
      - "${PORT}:3000"
    volumes:
      - ./log:/app/log
      - ./${RUNNER_FILE}:/app/${RUNNER_FILE}
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/hltv-manager/demos:/media/hltv-manager/demos
    environment:
      SITE_IP: "0.0.0.0"
      SITE_PORT: "3000"
      HLTV_DOCKER: ${HLTV_IMAGE}
      HLTV_DOCKER: "ghcr.io/wesstorn/hltv-files:${HLTV_VERSION}"
      HLT_DEMOS_DIR: "/media/hltv-manager"
    restart: unless-stopped